image: ghcr.io/streamingfast/substreams-gitpod:develop
tasks:
  - before: |
      # Authenticate with the substreams server
      export SUBSTREAMS_API_TOKEN=$(curl https://auth.dfuse.io/v1/auth/issue -s --data-binary '{"api_key":"'$STREAMINGFAST_KEY'"}' | jq -r .token)
